//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabloidWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabloidWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette table ne semble pas exister dans cette vue souhaitez-vous ajouter une jointure ?.
        /// </summary>
        internal static string add_join {
            get {
                return ResourceManager.GetString("add_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un filtre automatique à ce champ.
        /// </summary>
        internal static string AddAutomaticFilter {
            get {
                return ResourceManager.GetString("AddAutomaticFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une liste déroulante à cette vue pour cette table.
        /// </summary>
        internal static string AddComboForThisTable {
            get {
                return ResourceManager.GetString("AddComboForThisTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un nouvel import.
        /// </summary>
        internal static string AddImport {
            get {
                return ResourceManager.GetString("AddImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce projet ne contient pas de page de synthèse. Souhaitez vous en créer une?.
        /// </summary>
        internal static string AddNewSynthese {
            get {
                return ResourceManager.GetString("AddNewSynthese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du schéma par défaut n&apos;est pas défini souhaitez vous le définir et modifier l&apos;ensemble des tables?.
        /// </summary>
        internal static string AddSchema {
            get {
                return ResourceManager.GetString("AddSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajout {
            get {
                object obj = ResourceManager.GetObject("ajout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alerte.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transformer en alias.
        /// </summary>
        internal static string AliasTransform {
            get {
                return ResourceManager.GetString("AliasTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La jointure associée à ce champ n&apos;est pas visible pour ce type de visibilité, souhaitez vous modifier la visibilité de la jointure automatiquement?.
        /// </summary>
        internal static string alignJoinVisibility {
            get {
                return ResourceManager.GetString("alignJoinVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur durant l&apos;analyse.
        /// </summary>
        internal static string AnalyseError {
            get {
                return ResourceManager.GetString("AnalyseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse en cours.
        /// </summary>
        internal static string Analysing {
            get {
                return ResourceManager.GetString("Analysing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas utiliser la fonction d&apos;autoenrollement en dehors d&apos;une authentification Windows. Le mode d&apos;authentification va être modifié..
        /// </summary>
        internal static string AuthenticationAndAutoEnrollementError {
            get {
                return ResourceManager.GetString("AuthenticationAndAutoEnrollementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un champ avec un éditeur de type AutoComplete doit faire référence a un champ d&apos;une autre table..
        /// </summary>
        internal static string AutocompleteNeedExistingFieldUse {
            get {
                return ResourceManager.GetString("AutocompleteNeedExistingFieldUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette vue est générée automatiquement. Si vous la modifiez elle sera intégrée à votre personnalisation..
        /// </summary>
        internal static string Automatic_generated_view {
            get {
                return ResourceManager.GetString("Automatic_generated_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création des vues automatiques..
        /// </summary>
        internal static string AutomaticViewBuilding {
            get {
                return ResourceManager.GetString("AutomaticViewBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à la modification de la base :.
        /// </summary>
        internal static string Base_Modification_error {
            get {
                return ResourceManager.GetString("Base_Modification_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une jointure dans la vue {0} vers {1}.
        /// </summary>
        internal static string BuildSameJoin {
            get {
                return ResourceManager.GetString("BuildSameJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer les jointures dans la vue {0} pour joindre {1}.
        /// </summary>
        internal static string BuildSameJoinRecursively {
            get {
                return ResourceManager.GetString("BuildSameJoinRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de déterminer la clef primaire pour cette table..
        /// </summary>
        internal static string CantFindPrimaryKey {
            get {
                return ResourceManager.GetString("CantFindPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez modifié le schéma par défaut. Souhaitez-vous modifier le schéma pour l&apos;ensemble des vues?.
        /// </summary>
        internal static string ChangeProjectSchema {
            get {
                return ResourceManager.GetString("ChangeProjectSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement.
        /// </summary>
        internal static string Chargement {
            get {
                return ResourceManager.GetString("Chargement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez au moins une jointure automatique à créer !.
        /// </summary>
        internal static string ChooseOnAutomaticJoinAtLeast {
            get {
                return ResourceManager.GetString("ChooseOnAutomaticJoinAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nettoyage.
        /// </summary>
        internal static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nettoyage..
        /// </summary>
        internal static string Cleanning {
            get {
                return ResourceManager.GetString("Cleanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous la suppression de {0}({1}) de la vue {2}?.
        /// </summary>
        internal static string Confirm_supp {
            get {
                return ResourceManager.GetString("Confirm_supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous la suppression de la vue {0}({1})?.
        /// </summary>
        internal static string Confirm_supp_view {
            get {
                return ResourceManager.GetString("Confirm_supp_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous cette suppression?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous la suppression de cette vue?.
        /// </summary>
        internal static string ConfirmDeleteView {
            get {
                return ResourceManager.GetString("ConfirmDeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe de confirmation ne correspond pas!.
        /// </summary>
        internal static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seul les relations de type N:1 sont prises en charge!.
        /// </summary>
        internal static string ConvertOnlyN1Join {
            get {
                return ResourceManager.GetString("ConvertOnlyN1Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convertir la liste en tableau.
        /// </summary>
        internal static string ConvertToComplexList {
            get {
                return ResourceManager.GetString("ConvertToComplexList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convertir en liste.
        /// </summary>
        internal static string ConvertToList {
            get {
                return ResourceManager.GetString("ConvertToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette cellule ne fait pas référence à un indicateur. Souhaitez-vous en ajouter un?.
        /// </summary>
        internal static string CreateIndic {
            get {
                return ResourceManager.GetString("CreateIndic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création de jointure.
        /// </summary>
        internal static string CreateJoin {
            get {
                return ResourceManager.GetString("CreateJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez vous utiliser un champ de la base ou utiliser un champ créé dans l&apos;instruction select? Cliquiez sur oui pour utiliser un champ de la base..
        /// </summary>
        internal static string CreateOrUseField {
            get {
                return ResourceManager.GetString("CreateOrUseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnalisation du web.config..
        /// </summary>
        internal static string CustomingConfig {
            get {
                return ResourceManager.GetString("CustomingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les vues roles, utilisateur et perso sont des vues système? Si vous ne les avez pas personnalisées, il est recommandé de laisser tabloid les gérer automatiquement. Souhaitez vous les supprimer?.
        /// </summary>
        internal static string CustumRoleUsed {
            get {
                return ResourceManager.GetString("CustumRoleUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette Base de données n&apos;existe pas souhaitez-vous la créer?.
        /// </summary>
        internal static string DataBaseNotExist {
            get {
                return ResourceManager.GetString("DataBaseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des données..
        /// </summary>
        internal static string DatabaseRead {
            get {
                return ResourceManager.GetString("DatabaseRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affichage des données..
        /// </summary>
        internal static string DataDisplaying {
            get {
                return ResourceManager.GetString("DataDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import de la base.
        /// </summary>
        internal static string dbImport {
            get {
                return ResourceManager.GetString("dbImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Décroissant.
        /// </summary>
        internal static string Decreasing {
            get {
                return ResourceManager.GetString("Decreasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous le suppression?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous la suppression définitive de la fonction &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteFunctionConfirm {
            get {
                return ResourceManager.GetString("DeleteFunctionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap detail2 {
            get {
                object obj = ResourceManager.GetObject("detail2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire sélectionné n&apos;existe pas!.
        /// </summary>
        internal static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention la désactivation du module supprimera la table contenant les informations de ce dernier. Il ne sera pas possible de les récupérer. Confirmez vous cette opération?.
        /// </summary>
        internal static string DisableModule {
            get {
                return ResourceManager.GetString("DisableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la vue correspondante.
        /// </summary>
        internal static string DisplayCorrespondigView {
            get {
                return ResourceManager.GetString("DisplayCorrespondigView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la jointure correspondante.
        /// </summary>
        internal static string DisplayCorrespondingJoin {
            get {
                return ResourceManager.GetString("DisplayCorrespondingJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à affichée uniquement.
        /// </summary>
        internal static string DisplayOnly {
            get {
                return ResourceManager.GetString("DisplayOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dump de la base.
        /// </summary>
        internal static string DumpDataBase {
            get {
                return ResourceManager.GetString("DumpDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;édition .
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous vider la corbeille avant de la désactiver?.
        /// </summary>
        internal static string EmptyTrash {
            get {
                return ResourceManager.GetString("EmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enrg {
            get {
                object obj = ResourceManager.GetObject("enrg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de lecture du fichier de configuration\r.
        /// </summary>
        internal static string ErrorReadingConfigFile {
            get {
                return ResourceManager.GetString("ErrorReadingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export en cours.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ provient d&apos;une jointure, souhaitez vous supprimer la jointure?.
        /// </summary>
        internal static string Field_in_join_remove_join {
            get {
                return ResourceManager.GetString("Field_in_join_remove_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom de champ existe déja dans la base. Merci de le modifier..
        /// </summary>
        internal static string FieldAlreadyExist {
            get {
                return ResourceManager.GetString("FieldAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du champ est obligatoire..
        /// </summary>
        internal static string FieldNameNeeded {
            get {
                return ResourceManager.GetString("FieldNameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse du fichier.
        /// </summary>
        internal static string FileAnalysis {
            get {
                return ResourceManager.GetString("FileAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez le dossier contenant l&apos;ensemble du site..
        /// </summary>
        internal static string folder_site_selection {
            get {
                return ResourceManager.GetString("folder_site_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Génération de l&apos;export.
        /// </summary>
        internal static string GeneratingExport {
            get {
                return ResourceManager.GetString("GeneratingExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Génération du site web.
        /// </summary>
        internal static string GeneratingWebSite {
            get {
                return ResourceManager.GetString("GeneratingWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Graphique.
        /// </summary>
        internal static string Graphic {
            get {
                return ResourceManager.GetString("Graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  a été ajouté..
        /// </summary>
        internal static string Have_been_added {
            get {
                return ResourceManager.GetString("Have_been_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à caché.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise en place du moteur.
        /// </summary>
        internal static string ImportBuildEngine {
            get {
                return ResourceManager.GetString("ImportBuildEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction des fichiers.
        /// </summary>
        internal static string ImportExtractFile {
            get {
                return ResourceManager.GetString("ImportExtractFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie des fichiers annexes.
        /// </summary>
        internal static string ImportFilesCopying {
            get {
                return ResourceManager.GetString("ImportFilesCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une des lignes de votre tableau de correspondance est incomplète..
        /// </summary>
        internal static string ImportIncorrectExcelLine {
            get {
                return ResourceManager.GetString("ImportIncorrectExcelLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préparation de l&apos;import.
        /// </summary>
        internal static string ImportPrepare {
            get {
                return ResourceManager.GetString("ImportPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail de l&apos;import.
        /// </summary>
        internal static string ImportReport {
            get {
                return ResourceManager.GetString("ImportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restauration en cours.
        /// </summary>
        internal static string ImportRestauration {
            get {
                return ResourceManager.GetString("ImportRestauration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Croissant.
        /// </summary>
        internal static string Increasing {
            get {
                return ResourceManager.GetString("Increasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation.
        /// </summary>
        internal static string Initiating {
            get {
                return ResourceManager.GetString("Initiating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} lie &quot;{1}&quot; à &quot;{2}&quot; utilisez le bouton ci-dessous pour créer le contrainte..
        /// </summary>
        internal static string JoinWithNoConstraint_Description {
            get {
                return ResourceManager.GetString("JoinWithNoConstraint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Corriger sur tout le projet.
        /// </summary>
        internal static string JoinWithNoConstraintBuildAllConstraint {
            get {
                return ResourceManager.GetString("JoinWithNoConstraintBuildAllConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer la contrainte.
        /// </summary>
        internal static string JoinWithNoConstraintBuildConstraint {
            get {
                return ResourceManager.GetString("JoinWithNoConstraintBuildConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La jointure {0} de la vue {1} n&apos;est pas couverte par une contrainte..
        /// </summary>
        internal static string JoinWithNoConstraintTitle {
            get {
                return ResourceManager.GetString("JoinWithNoConstraintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement de la configuration.
        /// </summary>
        internal static string LoadingConfig {
            get {
                return ResourceManager.GetString("LoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des fichiers de configuration..
        /// </summary>
        internal static string LodingConfigFiles {
            get {
                return ResourceManager.GetString("LodingConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des styles cartographiques..
        /// </summary>
        internal static string LodingGeoStyle {
            get {
                return ResourceManager.GetString("LodingGeoStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier spécifié pour le stockage des logs est absent..
        /// </summary>
        internal static string Log_file_exist {
            get {
                return ResourceManager.GetString("Log_file_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ &apos;Identifiant Windows&apos; ne peut être vide!.
        /// </summary>
        internal static string LoginCouldnotbeempty {
            get {
                return ResourceManager.GetString("LoginCouldnotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D&apos;autre table sont liées à la table &apos;{tableName}&apos; :{pucePatern}{string.Join(.
        /// </summary>
        internal static string lookFor1NJoinLinkedTable {
            get {
                return ResourceManager.GetString("lookFor1NJoinLinkedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publipostage.
        /// </summary>
        internal static string Mailing {
            get {
                return ResourceManager.GetString("Mailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Converssion réussie..
        /// </summary>
        internal static string MainForm_convertisseur1x2xToolStripMenuItem_Click_Converssion_réussie_ {
            get {
                return ResourceManager.GetString("MainForm_convertisseur1x2xToolStripMenuItem_Click_Converssion_réussie_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un fichier portant le nom web.bak existe déja. Souhaitez vous l&apos;écraser?.
        /// </summary>
        internal static string MainForm_convertisseur1x2xToolStripMenuItem_Click_Un_fichier_portant_le_nom_web_bak_existe_déja__Souhaitez_vous_l_écraser_ {
            get {
                return ResourceManager.GetString("MainForm_convertisseur1x2xToolStripMenuItem_Click_Un_fichier_portant_le_nom_web_b" +
                        "ak_existe_déja__Souhaitez_vous_l_écraser_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce dossier ne contient pas de fichier config.web.
        /// </summary>
        internal static string MainForm_ReadWebConfig_Ce_dossier_ne_contient_pas_de_fichier_config_web {
            get {
                return ResourceManager.GetString("MainForm_ReadWebConfig_Ce_dossier_ne_contient_pas_de_fichier_config_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés de .
        /// </summary>
        internal static string MainForm_SetTableProperties_Propriétés_de_ {
            get {
                return ResourceManager.GetString("MainForm_SetTableProperties_Propriétés_de_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le menu a été créé avec succés..
        /// </summary>
        internal static string Menu_creation_success {
            get {
                return ResourceManager.GetString("Menu_creation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de masse.
        /// </summary>
        internal static string MultiSMS {
            get {
                return ResourceManager.GetString("MultiSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le schéma par défaut ne correspond pas au non de la base souhaitez-vous le corriger?.
        /// </summary>
        internal static string MySQLDifferentBaseName {
            get {
                return ResourceManager.GetString("MySQLDifferentBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de connection vérifiez les paramètres 
        ///.
        /// </summary>
        internal static string NewFromBaseForm_btn_Click_ {
            get {
                return ResourceManager.GetString("NewFromBaseForm_btn_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récupération des Tables.
        /// </summary>
        internal static string NewFromBaseForm_btn_Click_Récupération_des_Tables {
            get {
                return ResourceManager.GetString("NewFromBaseForm_btn_Click_Récupération_des_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La table {0} ne contient pas les champs par défaut pour le fonctionnement de Tabloïd!
        ///
        ///Les champs suivants sont abscents :
        ///
        ///	- {1}
        ///
        ///Souhaitez-vous les créer ?.
        /// </summary>
        internal static string NewFromBaseForm_GetTable_ {
            get {
                return ResourceManager.GetString("NewFromBaseForm_GetTable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les tables suivantes sont absentes :
        ///
        ///	- {0}
        ///
        /// Elles sont utile au fonctionnement de Tabloïd!
        ///
        ///Souhaitez-vous les créer ?.
        /// </summary>
        internal static string NewFromBaseForm_tables_inutiles {
            get {
                return ResourceManager.GetString("NewFromBaseForm_tables_inutiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune jointure vers cette table n&apos;existe. Tabloïd peut la créer pour vous. Souhaitez vous la créer?.
        /// </summary>
        internal static string NoJoinCreate {
            get {
                return ResourceManager.GetString("NoJoinCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à non déterminée.
        /// </summary>
        internal static string NotDefine {
            get {
                return ResourceManager.GetString("NotDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le dossier sélectionné ne semble pas être un dossier tabloïd. Confirmez-vous la suppression de son contenu?.
        /// </summary>
        internal static string NotTabloidFolderConfirm {
            get {
                return ResourceManager.GetString("NotTabloidFolderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  - le moteur est à jour..
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le menu paramètres n&apos;a pas été trouvé (vérifiez l&apos;othographe)....
        /// </summary>
        internal static string Parameters_menu_not_found {
            get {
                return ResourceManager.GetString("Parameters_menu_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit ce composer de 8 caractères ou plus, de lettre, nombre et caractères spéciaux..
        /// </summary>
        internal static string PasswordRegExpMess {
            get {
                return ResourceManager.GetString("PasswordRegExpMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie des fichiers de personnalisation.
        /// </summary>
        internal static string PersFilesCopy {
            get {
                return ResourceManager.GetString("PersFilesCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Textes prédefinis.
        /// </summary>
        internal static string PreDefineText {
            get {
                return ResourceManager.GetString("PreDefineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication.
        /// </summary>
        internal static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication en cours.
        /// </summary>
        internal static string Publishing {
            get {
                return ResourceManager.GetString("Publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champ de référence pour la table {0} :.
        /// </summary>
        internal static string RefFieldForTable {
            get {
                return ResourceManager.GetString("RefFieldForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez vous également le supprimer dans la base de donnée?.
        /// </summary>
        internal static string Remove_from_database {
            get {
                return ResourceManager.GetString("Remove_from_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de supprimer la jointure &apos;{0}&apos;. Confirmez vous cette opération?.
        /// </summary>
        internal static string Remove_join {
            get {
                return ResourceManager.GetString("Remove_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez vous également supprimer la table dans la base de donnée?.
        /// </summary>
        internal static string Remove_view_database {
            get {
                return ResourceManager.GetString("Remove_view_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression des fichiers et dossiers..
        /// </summary>
        internal static string RemovingFolderFiles {
            get {
                return ResourceManager.GetString("RemovingFolderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ancien nom : .
        /// </summary>
        internal static string RenameOldName {
            get {
                return ResourceManager.GetString("RenameOldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au moins un fichier de configuration existe déja souhaitez vous le remplacer?.
        /// </summary>
        internal static string ReplaceConfigFile {
            get {
                return ResourceManager.GetString("ReplaceConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrez sous.
        /// </summary>
        internal static string Save_as {
            get {
                return ResourceManager.GetString("Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde en cours.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement de la configuration..
        /// </summary>
        internal static string SavingConfig {
            get {
                return ResourceManager.GetString("SavingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur au cours de la sauvegarde :.
        /// </summary>
        internal static string SavingError {
            get {
                return ResourceManager.GetString("SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le schéma demandé existe déjà. Si vous souhaitez remplacer ce schéma utilisez le bouton &apos;oui&apos; attention toutes les données du schéma actuel seront supprimées..
        /// </summary>
        internal static string SchemaAlreadyExist {
            get {
                return ResourceManager.GetString("SchemaAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un filtre de recherche .
        /// </summary>
        internal static string Search_filter {
            get {
                return ResourceManager.GetString("Search_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez le fichier à importer.
        /// </summary>
        internal static string SelectImportFile {
            get {
                return ResourceManager.GetString("SelectImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de sélectionnez un indicateur..
        /// </summary>
        internal static string SelectIndic {
            get {
                return ResourceManager.GetString("SelectIndic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez une jointure pour poursuivre cette opération!.
        /// </summary>
        internal static string SelectJoin {
            get {
                return ResourceManager.GetString("SelectJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer un titre pour ce champ..
        /// </summary>
        internal static string SetFieldTitle {
            get {
                return ResourceManager.GetString("SetFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi simple.
        /// </summary>
        internal static string SimpleSMS {
            get {
                return ResourceManager.GetString("SimpleSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de copie des fichiers sources vérifiez les droits sur le dossier spécifié et l&apos;installation du Wizard..
        /// </summary>
        internal static string SourceFileCopyError {
            get {
                return ResourceManager.GetString("SourceFileCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet {0} - dossier {1} - version du projet {2} - version displonible {3}.
        /// </summary>
        internal static string StatusMatrix {
            get {
                return ResourceManager.GetString("StatusMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap suppr2 {
            get {
                object obj = ResourceManager.GetObject("suppr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom de table existe déja !.
        /// </summary>
        internal static string TableAlreadyExist {
            get {
                return ResourceManager.GetString("TableAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La table {0} semble ne plus exister. Vérifiez votre base..
        /// </summary>
        internal static string tableNotExist {
            get {
                return ResourceManager.GetString("tableNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer la vue.
        /// </summary>
        internal static string TableWithNoViewCreateView {
            get {
                return ResourceManager.GetString("TableWithNoViewCreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Renommer la table.
        /// </summary>
        internal static string TableWithNoViewRenameTable {
            get {
                return ResourceManager.GetString("TableWithNoViewRenameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette table est présente dans la base et ne dispose pas de vue associée..
        /// </summary>
        internal static string TableWithNoViewTitle {
            get {
                return ResourceManager.GetString("TableWithNoViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie des fichiers et dossiers Tabloid..
        /// </summary>
        internal static string TabloidFileCopy {
            get {
                return ResourceManager.GetString("TabloidFileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ .
        /// </summary>
        internal static string TheField {
            get {
                return ResourceManager.GetString("TheField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation....
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom de vue existe déja. Si vous souhaitez créer deux vues pour une même table saisissez un nom de vue différent.
        /// </summary>
        internal static string ViewNameAlreadyExist {
            get {
                return ResourceManager.GetString("ViewNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette vue fait référence à une table qui n&apos;existe pas..
        /// </summary>
        internal static string ViewWithNoTableTitle {
            get {
                return ResourceManager.GetString("ViewWithNoTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en lecture seule.
        /// </summary>
        internal static string WithReadOnly {
            get {
                return ResourceManager.GetString("WithReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La base actuelle ne semble pas implémenter la nouvelle gestion des roles de Tabloid. Shoutez vous la convertir ?.
        /// </summary>
        internal static string WrongConfigVersion {
            get {
                return ResourceManager.GetString("WrongConfigVersion", resourceCulture);
            }
        }
    }
}
